/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.quiz_application.App.Review;

import com.formdev.flatlaf.FlatLightLaf;
import com.mycompany.quiz_application.App.Login.Dashboard;
import com.mycompany.quiz_application.App.Records.QuizGroupRecords;
import com.mycompany.quiz_application.Globals;
import com.mycompany.quiz_application.dbConnector;
import com.mysql.cj.xdevapi.Result;
import java.awt.Color;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author yuzuki
 */
public class finishedQuiz extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(finishedQuiz.class.getName());
    private static Review_Query_Data review = new Review_Query_Data(new dbConnector());

    public static int id = 0;
    public static boolean isDone = false;

    public static int quizID = 0;
    public static ArrayList<Integer> quizGroup = new ArrayList<>();

    /**
     * Creates new form finishedQuiz
     */
    public finishedQuiz() {
        initComponents();

        displayData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        Review = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        table.setBackground(Color.WHITE);
        table.setFont(new java.awt.Font("Liberation Sans", 0, 14)); // NOI18N
        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "#", "ID", "Quiz Name", "Teacher", "remarks"
            }
        ));
        jScrollPane1.setViewportView(table);
        if (table.getColumnModel().getColumnCount() > 0) {
            table.getColumnModel().getColumn(0).setMinWidth(50);
            table.getColumnModel().getColumn(0).setPreferredWidth(50);
            table.getColumnModel().getColumn(0).setMaxWidth(50);
            table.getColumnModel().getColumn(1).setMinWidth(0);
            table.getColumnModel().getColumn(1).setMaxWidth(0);
            table.getColumnModel().getColumn(4).setMinWidth(70);
            table.getColumnModel().getColumn(4).setPreferredWidth(70);
            table.getColumnModel().getColumn(4).setMaxWidth(70);
        }

        jButton1.setBackground(new java.awt.Color(51, 51, 51));
        jButton1.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Back");
        jButton1.addActionListener(this::jButton1ActionPerformed);

        Review.setBackground(new java.awt.Color(51, 51, 51));
        Review.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        Review.setForeground(new java.awt.Color(255, 255, 255));
        Review.setText("View Answer");
        Review.addActionListener(this::ReviewActionPerformed);

        jButton3.setBackground(new java.awt.Color(51, 51, 51));
        jButton3.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Result");
        jButton3.addActionListener(this::jButton3ActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 654, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(Review, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(31, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Review, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ReviewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReviewActionPerformed
        // TODO add your handling code here:
        if (id == 0) {
            JOptionPane.showMessageDialog(this, "Selected row required !");
            return;
        }
        if (Globals.getInstance().getRoles().equals("Teacher") && !isDone) {
            JOptionPane.showMessageDialog(this, "No records Found !");
            return;
        }
        isDone = false;

        ReviewQuiz result = new ReviewQuiz();
        if (Globals.getInstance().getRoles().equals("Student")) {
            Globals.getInstance().setQuizGroupID(quizID);
        }; // its still the value from the previos selection

//        Globals.getInstance().setQuizGroupID(Globals.getInstance().getQuizGroupID() || quizID);
        Globals.getInstance().setStudentID(id);
        setVisible(false);
        result.displayData();
        result.setVisible(true);
        quizID = 0; //why didnt reset

    }//GEN-LAST:event_ReviewActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        if (id == 0) {
            JOptionPane.showMessageDialog(this, "Selected row required !");
            return;
        }
        if (Globals.getInstance().getRoles().equals("Teacher") && !isDone) {
            JOptionPane.showMessageDialog(this, "No records Found !");
            return;
        }
        QuizResult result = new QuizResult();
        if (Globals.getInstance().getRoles().equals("Student")) {
            Globals.getInstance().setQuizGroupID(quizID);
        }
        Globals.getInstance().setStudentID(id);
        setVisible(false);
        result.showResult();
        result.setVisible(true);
        quizID = 0; //why didnt reset


    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:

        if (Globals.getInstance().getRoles().equals("Teacher")) {
            QuizGroupRecords rev = new QuizGroupRecords();
            rev.setWindow(true);
        } else {

            Dashboard dash = new Dashboard();
            dash.setWindow(true);

        }

        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed
    public void displayData() {

        DefaultTableModel model = (DefaultTableModel) table.getModel();
        model.setRowCount(0); // clear previous data

        quizGroup.clear();
        try {
            ResultSet list;

            if (Globals.getInstance().getRoles().equals("Teacher")) {

                review.setQuizGroupID(Globals.getInstance().getQuizGroupID());
                review.setTeacherID(Globals.getInstance().getTeacherID());

                list = review.displayStudentList();

                int counter = 0;

                while (list.next()) {
                    model.addRow(new Object[]{
                        ++counter,
                        list.getInt("studentID"),
                        list.getString("quizName"),
                        list.getString("fullname"),
                        "done".equals(list.getString("status")) ? "done" : "not finished"
                    });
                    System.out.println(list.getInt("studentID"));
                }

                // CHANGE COLUMN NAME (index 3 = fullname)
                table.getColumnModel().getColumn(3).setHeaderValue("Student Name");
                table.getTableHeader().repaint();

            } else {

                review.setStudentID(Globals.getInstance().getStudentID());

                list = review.displayQuiz();

                int counter = 0;

                while (list.next()) {
                    model.addRow(new Object[]{
                        ++counter,
                        list.getInt("studentID"),
                        list.getString("quizName"),
                        list.getString("fullname"),
                        "done".equals(list.getString("status")) ? "done" : "not finished"
                    });

                    quizGroup.add(list.getInt("quizGroupID"));
                }
//                       table.getColumnModel().getColumn(3).setHeaderValue("Full Name");
//                table.getTableHeader().repaint();
            }

        } catch (SQLException ex) {
            System.getLogger(finishedQuiz.class.getName())
                    .log(System.Logger.Level.ERROR, (String) null, ex);
        }

        table.addMouseListener(new MouseAdapter() {
            public void mouseClicked(MouseEvent e) {
                if (e.getClickCount() == 1) {
                    int row = table.getSelectedRow();

                    int modelRow = table.convertRowIndexToModel(row);

                    DefaultTableModel model = (DefaultTableModel) table.getModel();

                    Object secondColumnValue = model.getValueAt(modelRow, 1);

                    if (Globals.getInstance().getRoles().equals("Teacher")) {
                        Object isFInish = model.getValueAt(modelRow, 4);
                        isDone = (isFInish.equals("done")) ? true : false;
                    }
                    id = (int) secondColumnValue;

                    if (modelRow < quizGroup.size()) {
                        quizID = quizGroup.get(modelRow);
                    }

                    System.out.println("Selected Row: " + quizID);
                    System.out.println("2nd Column Value: " + secondColumnValue);
                }
            }
        });
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        try {

            FlatLightLaf.setup();
        } catch (Exception e) {
        }
        java.awt.EventQueue.invokeLater(() -> new finishedQuiz().setVisible(true));

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Review;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable table;
    // End of variables declaration//GEN-END:variables
}
