/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.quiz_application.App.Review;

import com.formdev.flatlaf.FlatLightLaf;
import static com.mycompany.quiz_application.App.Review.QuizResult.log;
import com.mycompany.quiz_application.Globals;
import com.mycompany.quiz_application.dbConnector;
import com.mysql.cj.xdevapi.Result;
import java.awt.Color;
import java.awt.Component;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.JTextArea;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableCellRenderer;

/**
 *
 * @author yuzuki
 */
public class ReviewQuiz extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ReviewQuiz.class.getName());
    private static Review_Query_Data review = new Review_Query_Data(new dbConnector());

    public static int id = 0;

    /**
     * Creates new form finishedQuiz
     */
    public ReviewQuiz() {
        initComponents();

        displayData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        table.setBackground(Color.WHITE);
        table.setFont(table.getFont().deriveFont(table.getFont().getSize()+5f));
        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "#", "", "Question", "Your Answer", "Corrected Answer"
            }
        ));
        jScrollPane1.setViewportView(table);
        if (table.getColumnModel().getColumnCount() > 0) {
            table.getColumnModel().getColumn(0).setMinWidth(50);
            table.getColumnModel().getColumn(0).setPreferredWidth(50);
            table.getColumnModel().getColumn(0).setMaxWidth(50);
            table.getColumnModel().getColumn(1).setMinWidth(80);
            table.getColumnModel().getColumn(1).setPreferredWidth(80);
            table.getColumnModel().getColumn(1).setMaxWidth(80);
        }

        jButton1.setBackground(new java.awt.Color(51, 51, 51));
        jButton1.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Back");
        jButton1.addActionListener(this::jButton1ActionPerformed);

        jLabel1.setFont(new java.awt.Font("Liberation Sans", 1, 36)); // NOI18N
        jLabel1.setText("Review Test");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1336, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(31, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        finishedQuiz quiz = new finishedQuiz();
        quiz.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed
    public void displayData() {

        review.setQuizGroupID(Globals.getInstance().getQuizGroupID());
        review.setStudentID(Globals.getInstance().getStudentID());

        DefaultTableModel model = (DefaultTableModel) table.getModel();

        try {
            ResultSet list = review.displayReview();
            int counter = 0;
            char mark;
            String quizAnswer = "";
            String studentAnswerx = "";
            model.setRowCount(0); // clear table

            while (list.next()) {

                if (list.getInt("studentAnswer") == list.getInt("quizAnswer")) {
                    mark = '\u2713'; // ✓ correct
                } else {
                    mark = '\u2717'; // ✗ wrong
                }

                if (list.getInt("quizType") == 2) {
                    quizAnswer = list.getInt("quizAnswer") != 1 ? "True" : "False";
                    studentAnswerx = (list.getObject("studentAnswer", Integer.class) == null)
                            ? "No Answer"
                            : (list.getInt("studentAnswer") == 1 ? "True" : "False");
                } else if (list.getInt("quizType") == 1) {
                    String[] cityArray = list.getString("questionList").split(",");

                    quizAnswer = cityArray[list.getInt("quizAnswer")];
                    studentAnswerx = cityArray[list.getInt("studentAnswer")];

                }
                model.addRow(new Object[]{
                    ++counter,
                    mark,
                    list.getString("displayQuestion"),
                    studentAnswerx,
                    quizAnswer
                });
            }

            // AUTO RESIZE ROW HEIGHT + COLUMN WIDTH (single method)
            for (int row = 0; row < table.getRowCount(); row++) {
                int maxHeight = table.getRowHeight();

                for (int col = 0; col < table.getColumnCount(); col++) {
                    TableCellRenderer renderer = table.getCellRenderer(row, col);
                    Component comp = table.prepareRenderer(renderer, row, col);
                    maxHeight = Math.max(maxHeight, comp.getPreferredSize().height);
                }

                table.setRowHeight(row, maxHeight);
            }

            for (int col = 0; col < table.getColumnCount(); col++) {
                int maxWidth = 50;

                for (int row = 0; row < table.getRowCount(); row++) {
                    TableCellRenderer renderer = table.getCellRenderer(row, col);
                    Component comp = table.prepareRenderer(renderer, row, col);
                    maxWidth = Math.max(maxWidth, comp.getPreferredSize().width);
                }

                table.getColumnModel().getColumn(col).setPreferredWidth(maxWidth + 10);
            }

            // Enable wrapping for long text (important for displayQuestion column)
            table.getColumnModel().getColumn(2).setCellRenderer(new DefaultTableCellRenderer() {
                @Override
                public Component getTableCellRendererComponent(
                        JTable table, Object value, boolean isSelected,
                        boolean hasFocus, int row, int column) {

                    JTextArea area = new JTextArea(value == null ? "" : value.toString());
                    area.setLineWrap(true);
                    area.setWrapStyleWord(true);
                    area.setOpaque(true);

                    return area;
                }
            });

        } catch (SQLException ex) {
            System.getLogger(ReviewQuiz.class.getName())
                    .log(System.Logger.Level.ERROR, (String) null, ex);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        try {

            FlatLightLaf.setup();
        } catch (Exception e) {
        }
        java.awt.EventQueue.invokeLater(() -> new ReviewQuiz().setVisible(true));

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable table;
    // End of variables declaration//GEN-END:variables
}
