/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.quiz_application.App.Quiz;

import com.mycompany.quiz_application.dbConnector;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.time.LocalTime;
import java.util.ArrayList;
import java.util.List;
import javax.swing.AbstractButton;
import javax.swing.ButtonModel;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JRadioButton;
import javax.swing.Timer;
import javax.swing.text.View;

/**
 *
 * @author yuzuki
 */
public class appQuiz extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(appQuiz.class.getName());

    static dbConnector conn = new dbConnector();
    static QuizLog log = new QuizLog(conn);
    private Timer timer;
    private int counter = 0;
    private int totalQuizes = 0;

    /**
     * Creates new form appQuiz
     */
    public appQuiz() {
        initComponents();
        customInit();
        initializeQuiz();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    private List<String> quizQuestions = new ArrayList<>();
    private List<String> listQuestion = new ArrayList<>();
    private int currentIndex = 0;

    private void initializeQuiz() {
        Quiz quiz = new Quiz(conn);
        quiz.setQuizGroupID(1);
        ResultSet quizList = quiz.displayQuiz();

        try {
            while (quizList.next()) {
                // Assuming column name is "question"
                listQuestion.add(quizList.getString("questionList"));
                quizQuestions.add(quizList.getString("displayQuestion"));

                ++totalQuizes;
            }

            // Show first quiz
            if (!quizQuestions.isEmpty()) {
                labelDisplayQuiz.setText(quizQuestions.get(currentIndex));
                displayAnswerList(currentIndex);
                getCounter();
            }

        } catch (Exception e) {
            System.out.println(e);
        }
    }

    private void customInit() {
        buttonGroup1.add(selection_1);
        buttonGroup1.add(selection_2);
        buttonGroup1.add(selection_4);
        buttonGroup1.add(selection_6);

        // Stop existing timer if running
        if (timer != null && timer.isRunning()) {
            timer.stop();
        }

        // Reset counter
        counter = 0;

        // Create new timer
        timer = new Timer(1000, new ActionListener() { // 1000ms = 1 second
            @Override
            public void actionPerformed(ActionEvent e) {
                counter++;

                int minutes = counter / 60;
                int seconds = counter % 60;

                labelTimer.setText(String.format("%02d:%02d", minutes, seconds));
            }
        });

        timer.start();
    }

    private void restartTimer() {
        if (timer != null) {
            timer.stop();
        }

        counter = 0;
        labelTimer.setText("00:00");
        timer.start();
    }

    private void getCounter() {
        counterPage.setText("Page %d to %d".formatted(
                currentIndex + 1,
                totalQuizes
        ));
    }

    private void sendAnswer() {
        ButtonModel selectedModel = buttonGroup1.getSelection();

        log.setQuizID(1);
        log.setStudentID(1);
        log.setStudentAnswer(
                buttonGroup1.getSelection().getActionCommand());
        log.setTimestamp(LocalTime.of(0, 0, counter));
        log.createQuiz();
    }
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        labelDisplayQuiz = new javax.swing.JLabel();
        box1 = new javax.swing.JPanel();
        selection_1 = new javax.swing.JRadioButton();
        box2 = new javax.swing.JPanel();
        selection_2 = new javax.swing.JRadioButton();
        box4 = new javax.swing.JPanel();
        selection_4 = new javax.swing.JRadioButton();
        box6 = new javax.swing.JPanel();
        selection_6 = new javax.swing.JRadioButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        labelTimer = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        counterPage = new javax.swing.JLabel();
        nextPage = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        labelDisplayQuiz.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        labelDisplayQuiz.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labelDisplayQuiz.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        String labelText = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec odio erat, pharetra quis sagittis quis, vehicula sed risus. Cras posuere et magna ac pretium. Nunc in venenatis est. Nunc et leo quis est bibendum pharetra vitae vel mi. ";

        selection_1.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N
        selection_1.setText("jRadioButton1");
        selection_1.addActionListener(this::selection_1ActionPerformed);

        javax.swing.GroupLayout box1Layout = new javax.swing.GroupLayout(box1);
        box1.setLayout(box1Layout);
        box1Layout.setHorizontalGroup(
            box1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(box1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(selection_1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        box1Layout.setVerticalGroup(
            box1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(box1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(selection_1)
                .addContainerGap(64, Short.MAX_VALUE))
        );

        selection_2.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N
        selection_2.setText("jRadioButton1");
        selection_2.addActionListener(this::selection_2ActionPerformed);

        javax.swing.GroupLayout box2Layout = new javax.swing.GroupLayout(box2);
        box2.setLayout(box2Layout);
        box2Layout.setHorizontalGroup(
            box2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(box2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(selection_2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        box2Layout.setVerticalGroup(
            box2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(box2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(selection_2)
                .addContainerGap(68, Short.MAX_VALUE))
        );

        selection_4.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N
        selection_4.setText("jRadioButton1");
        selection_4.addActionListener(this::selection_4ActionPerformed);

        javax.swing.GroupLayout box4Layout = new javax.swing.GroupLayout(box4);
        box4.setLayout(box4Layout);
        box4Layout.setHorizontalGroup(
            box4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(box4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(selection_4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        box4Layout.setVerticalGroup(
            box4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(box4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(selection_4)
                .addContainerGap(87, Short.MAX_VALUE))
        );

        selection_6.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N
        selection_6.setText("jRadioButton1");
        selection_6.addActionListener(this::selection_6ActionPerformed);

        javax.swing.GroupLayout box6Layout = new javax.swing.GroupLayout(box6);
        box6.setLayout(box6Layout);
        box6Layout.setHorizontalGroup(
            box6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(box6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(selection_6)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        box6Layout.setVerticalGroup(
            box6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(box6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(selection_6)
                .addContainerGap(75, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(box6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(box4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(box2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(box1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(labelDisplayQuiz, javax.swing.GroupLayout.PREFERRED_SIZE, 921, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(20, 20, 20))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(labelDisplayQuiz, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(box1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(box2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(box4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(box6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7))
        );

        labelDisplayQuiz.setText("<html>%s</html>".formatted(labelText));

        jLabel2.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        jLabel2.setText("Time Left:");

        labelTimer.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        labelTimer.setText("00:00");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 95, Short.MAX_VALUE)
                .addComponent(labelTimer)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(labelTimer))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        jLabel9.setFont(new java.awt.Font("Liberation Sans", 0, 36)); // NOI18N
        jLabel9.setText("Simple Quiz Title");

        counterPage.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N
        counterPage.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        counterPage.setText("Quiz number x to y");
        counterPage.setToolTipText("");

        nextPage.setText("jButton1");
        nextPage.addActionListener(this::nextPageActionPerformed);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(counterPage)
                .addGap(490, 490, 490)
                .addComponent(nextPage, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(counterPage)
                    .addComponent(nextPage, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jLabel9)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(35, 35, 35)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void selection_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selection_1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_selection_1ActionPerformed

    private void selection_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selection_2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_selection_2ActionPerformed

    private void selection_4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selection_4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_selection_4ActionPerformed

    private void selection_6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selection_6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_selection_6ActionPerformed

    private void nextPageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextPageActionPerformed
        // TODO add your handling code here:
        sendAnswer(); // save current answer FIRST

        if (currentIndex < quizQuestions.size() - 1) {
            currentIndex++;
            labelDisplayQuiz.setText(quizQuestions.get(currentIndex));
            restartTimer();
            displayAnswerList(currentIndex);
            getCounter();
        } else {
            labelDisplayQuiz.setText("End of quiz");
            timer.stop();
            labelTimer.setText("00:00");
        }
    }//GEN-LAST:event_nextPageActionPerformed
    private void displayAnswerList(int currentIndex) {
        String[] output = listQuestion.get(currentIndex).split(",");

        JPanel[] boxes = {box1, box2, box4, box6};
        JRadioButton[] questions = {selection_1, selection_2, selection_4, selection_6};

        for (int i = 0; i < boxes.length; i++) {
            if (i < output.length && !output[i].trim().isEmpty()) {
                boxes[i].setVisible(true);
                questions[i].setActionCommand(String.valueOf(i));
                questions[i].setText(output[i].trim());
            } else {
                boxes[i].setVisible(false);
            }
        }

        // refresh layout after visibility changes
        box1.getParent().revalidate();
        box1.getParent().repaint();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new appQuiz().setVisible(true));

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel box1;
    private javax.swing.JPanel box2;
    private javax.swing.JPanel box4;
    private javax.swing.JPanel box6;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel counterPage;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel labelDisplayQuiz;
    private javax.swing.JLabel labelTimer;
    private javax.swing.JButton nextPage;
    private javax.swing.JRadioButton selection_1;
    private javax.swing.JRadioButton selection_2;
    private javax.swing.JRadioButton selection_4;
    private javax.swing.JRadioButton selection_6;
    // End of variables declaration//GEN-END:variables
}
