package com.mycompany.quiz_application.App.mainQuiz;

import static com.mycompany.quiz_application.App.mainQuiz.ListOfQuizes.id;
import com.mycompany.quiz_application.Globals;
import com.mycompany.quiz_application.dbConnector;
import java.sql.ResultSet;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JRadioButton;
import javax.swing.JTextArea;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author yuzuki
 */
public class addQuiz extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(addQuiz.class.getName());
    private static Quiz_Query_Data quiz = new Quiz_Query_Data(new dbConnector());

    /**
     * Creates new form addQuiz
     */
    public addQuiz() {
        initComponents();
        jButtonRadioComponents();
        customeComponents();
        editQuery();
    }

    private void customeComponents() {
        clearFields.setVisible(true);
        questionerBox.setVisible(false);
        true_false_Selection.setVisible(false);
        refreshWindow();
    }

    public void editQuery() {
        if (Globals.getInstance().getQueryMode().equals("edit")) {
            clearFields.setVisible(false);
            try {
                quiz.setQuizID(Globals.getInstance().getQuizID());
                System.err.println(Globals.getInstance().getQuizID());
                ResultSet set = quiz.displaySpecifyQuiz();
                while (set.next()) {
                    quizQuestion.setText(set.getString("displayQuestion"));
                    jComboBox1.setSelectedIndex(set.getInt("quizType"));
                    if (set.getInt("quizType") == 1) {

                        questionerBox.setVisible(true);
                        true_false_Selection.setVisible(false);
                        refreshWindow();
                        JTextArea[] textboxes = {Q1_text, Q2_text, Q3_text, Q4_text};
                        JRadioButton[] selectionButton = {Q1, Q2, Q3, Q4};
//                        System.out.println(set.getString("displayQuestion"));
                        String[] array = set.getString("questionList").split(",");
                        int count = -1;
                        for (JTextArea ta : textboxes) {
                            ++count;
                            ta.setText(array[count]);
                        }
                        selectionButton[set.getInt("quizAnswer")].setSelected(true);
                    } else if (set.getInt("quizType") == 2) {

                        questionerBox.setVisible(false);
                        true_false_Selection.setVisible(true);
                        JRadioButton[] truefalseSelection = {trueSelect, falseSelect};
                        System.out.println(set.getInt("quizType"));
                        truefalseSelection[set.getInt("quizAnswer")].setSelected(true);
                    }

                }
            } catch (Exception e) {
            }
        }
    }

    public void clearInputs() {
        // Clear question text
        quizQuestion.setText("");

        // Clear text areas
        JTextArea[] textboxes = {Q1_text, Q2_text, Q3_text, Q4_text};
        for (JTextArea ta : textboxes) {
            ta.setText("");
        }

        // Clear radio button selection
        JRadioButton[] selectionButton = {Q1, Q2, Q3, Q4};

        for (JRadioButton rb : selectionButton) {
            rb.setSelected(false);
        }

        // Optional: hide panels if needed
        questionerBox.setVisible(false);
        true_false_Selection.setVisible(false);

        Globals.getInstance().setQueryMode("");
        Globals.getInstance().setQuizID(0);
        jComboBox1.setSelectedIndex(0);
        System.out.println("The Fields is cleared");
    }

    private void jButtonRadioComponents() {
        JRadioButton[] selectionButton = {Q1, Q2, Q3, Q4};
        JRadioButton[] isTrueorFalse = {trueSelect, falseSelect};
//        JTextArea[] textboxes = {Q1_text, Q1_text, Q1_text, Q1_text};
        int counter = -1;
        for (JRadioButton selection : selectionButton) {
            buttonGroup1.add(selection);
            counter++;
            selection.setActionCommand(String.valueOf(counter));
//            selection[]
        }
        int counter2 = -1;
        for (JRadioButton selection : isTrueorFalse) {
            counter2++;
            buttonGroup2.add(selection);
            selection.setActionCommand(String.valueOf(counter2));
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        quizQuestion = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        questionerBox = new javax.swing.JPanel();
        Q1 = new javax.swing.JRadioButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        Q1_text = new javax.swing.JTextArea();
        Q2 = new javax.swing.JRadioButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        Q2_text = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        Q3_text = new javax.swing.JTextArea();
        jScrollPane5 = new javax.swing.JScrollPane();
        Q4_text = new javax.swing.JTextArea();
        Q4 = new javax.swing.JRadioButton();
        Q3 = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        true_false_Selection = new javax.swing.JPanel();
        trueSelect = new javax.swing.JRadioButton();
        falseSelect = new javax.swing.JRadioButton();
        clearFields = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N
        jLabel1.setText("Questions:");

        quizQuestion.setColumns(20);
        quizQuestion.setRows(5);
        jScrollPane1.setViewportView(quizQuestion);

        jLabel2.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N
        jLabel2.setText("Quiz Type:");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "---", "Multiple Choice", "True or False" }));
        jComboBox1.addActionListener(this::jComboBox1ActionPerformed);

        Q1.setText("Q1");

        Q1_text.setColumns(20);
        Q1_text.setRows(5);
        jScrollPane2.setViewportView(Q1_text);

        Q2.setText("Q2");

        Q2_text.setColumns(20);
        Q2_text.setRows(5);
        jScrollPane3.setViewportView(Q2_text);

        Q3_text.setColumns(20);
        Q3_text.setRows(5);
        Q3_text.setText("Q3_text");
        jScrollPane4.setViewportView(Q3_text);

        Q4_text.setColumns(20);
        Q4_text.setRows(5);
        jScrollPane5.setViewportView(Q4_text);

        Q4.setText("Q4");

        Q3.setText("Q3");

        javax.swing.GroupLayout questionerBoxLayout = new javax.swing.GroupLayout(questionerBox);
        questionerBox.setLayout(questionerBoxLayout);
        questionerBoxLayout.setHorizontalGroup(
            questionerBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(questionerBoxLayout.createSequentialGroup()
                .addGroup(questionerBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(questionerBoxLayout.createSequentialGroup()
                        .addComponent(Q4)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 597, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(questionerBoxLayout.createSequentialGroup()
                        .addComponent(Q3)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 597, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(questionerBoxLayout.createSequentialGroup()
                        .addComponent(Q1)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 597, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, questionerBoxLayout.createSequentialGroup()
                .addComponent(Q2)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 597, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        questionerBoxLayout.setVerticalGroup(
            questionerBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(questionerBoxLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(questionerBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Q1))
                .addGap(18, 18, 18)
                .addGroup(questionerBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Q2))
                .addGap(18, 18, 18)
                .addGroup(questionerBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Q3))
                .addGap(18, 18, 18)
                .addGroup(questionerBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Q4))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jButton1.setFont(new java.awt.Font("Liberation Sans", 0, 20)); // NOI18N
        jButton1.setText("Cancel");
        jButton1.addActionListener(this::jButton1ActionPerformed);

        jButton2.setFont(new java.awt.Font("Liberation Sans", 0, 20)); // NOI18N
        jButton2.setText("Save");
        jButton2.addActionListener(this::jButton2ActionPerformed);

        trueSelect.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N
        trueSelect.setText("True");

        falseSelect.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N
        falseSelect.setText("False");

        javax.swing.GroupLayout true_false_SelectionLayout = new javax.swing.GroupLayout(true_false_Selection);
        true_false_Selection.setLayout(true_false_SelectionLayout);
        true_false_SelectionLayout.setHorizontalGroup(
            true_false_SelectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, true_false_SelectionLayout.createSequentialGroup()
                .addContainerGap(190, Short.MAX_VALUE)
                .addComponent(trueSelect, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(falseSelect, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(190, Short.MAX_VALUE))
        );
        true_false_SelectionLayout.setVerticalGroup(
            true_false_SelectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(true_false_SelectionLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(true_false_SelectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(trueSelect)
                    .addComponent(falseSelect))
                .addContainerGap(40, Short.MAX_VALUE))
        );

        clearFields.setText("Clear");
        clearFields.addActionListener(this::clearFieldsActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel2)
                            .addGap(18, 18, 18)
                            .addComponent(jComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addComponent(jLabel1)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 688, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(true_false_Selection, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(questionerBox, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(clearFields, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(41, 41, 41)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(22, 22, 22)))
                .addGap(14, 14, 14))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addComponent(questionerBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(true_false_Selection, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, 65, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 65, Short.MAX_VALUE)
                    .addComponent(clearFields, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(31, 31, 31))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        JTextArea[] textboxes = {Q1_text, Q2_text, Q3_text, Q4_text};

        if (!isFormValid(textboxes)) {
            return;
        }

        quiz.setQuizGroupID(Globals.getInstance().getQuizGroupID());
        quiz.setQuizType(String.valueOf(jComboBox1.getSelectedIndex()));
        quiz.setDisplayQuestion(quizQuestion.getText());

        if (jComboBox1.getSelectedIndex() == 1) {

            ArrayList<String> listAnswer = new ArrayList<>();
            for (JTextArea ta : textboxes) {
                listAnswer.add(ta.getText());
            }

            quiz.setQuestionList(listAnswer);
            quiz.setQuizAnswer(buttonGroup1.getSelection().getActionCommand());

        } else if (jComboBox1.getSelectedIndex() == 2) {
            quiz.setQuestionList(new ArrayList<>());
            quiz.setQuizAnswer(buttonGroup2.getSelection().getActionCommand());
//            System.out.println(buttonGroup2.getSelection().getActionCommand());
        }

        if (Globals.getInstance().getQueryMode().equals("edit")) {
            JOptionPane.showMessageDialog(this, "Successfuly update a quiz");

            quiz.setQuizID(Globals.getInstance().getQuizID());
            quiz.updateQuiz();

            clearInputs();
            ListOfQuizes mainQuiz = new ListOfQuizes();
            mainQuiz.setVisible(true);
            setVisible(false);

        } else {
            JOptionPane.showMessageDialog(this, "Successfuly add a new quiz");

            quiz.createQuiz();
        }
        clearInputs();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
        if (jComboBox1.getSelectedIndex() == 1) {
            questionerBox.setVisible(true);
            true_false_Selection.setVisible(false);
            refreshWindow();

        } else if (jComboBox1.getSelectedIndex() == 2) {
            true_false_Selection.setVisible(true);
            questionerBox.setVisible(false);
            refreshWindow();
        } else {
            customeComponents();
        }

    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:

        clearInputs();
        ListOfQuizes mainQuiz = new ListOfQuizes();
        mainQuiz.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void clearFieldsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearFieldsActionPerformed
        // TODO add your handling code here:
        clearInputs();
    }//GEN-LAST:event_clearFieldsActionPerformed

    private boolean isFormValid(JTextArea[] textboxes) {

        int type = jComboBox1.getSelectedIndex();

        if (type == 0) {
            JOptionPane.showMessageDialog(this, "Please select a quiz type.");
            return false;
        }

        if (quizQuestion.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Question field cannot be empty.");
            return false;
        }

        if (type == 1) {
            for (JTextArea ta : textboxes) {
                if (ta.getText().trim().isEmpty()) {
                    JOptionPane.showMessageDialog(this, "All answer fields must be filled.");
                    return false;
                }
            }

            if (buttonGroup1.getSelection() == null) {
                JOptionPane.showMessageDialog(this, "Please select the correct answer.");
                return false;
            }

        } else if (type == 2) {
            if (buttonGroup2.getSelection() == null) {
                JOptionPane.showMessageDialog(this, "Please select the correct answer.");
                return false;
            }
        }

        return true; // all conditions passed
    }

    private void refreshWindow() {
        pack();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new addQuiz().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton Q1;
    private javax.swing.JTextArea Q1_text;
    private javax.swing.JRadioButton Q2;
    private javax.swing.JTextArea Q2_text;
    private javax.swing.JRadioButton Q3;
    private javax.swing.JTextArea Q3_text;
    private javax.swing.JRadioButton Q4;
    private javax.swing.JTextArea Q4_text;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JButton clearFields;
    private javax.swing.JRadioButton falseSelect;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JPanel questionerBox;
    private javax.swing.JTextArea quizQuestion;
    private javax.swing.JRadioButton trueSelect;
    private javax.swing.JPanel true_false_Selection;
    // End of variables declaration//GEN-END:variables
}
